SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE SCHEMA IF NOT EXISTS `openDataProject` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `openDataProject` ;
DROP TABLE IF EXISTS `openDataProject`.`trainstations` ;
CREATE TABLE IF NOT EXISTS `openDataProject`.`trainstations` (`trainstations_ID` INT NOT NULL,`x_koordinate` FLOAT NOT NULL,`y_koordinate` FLOAT NOT NULL,PRIMARY KEY (`trainstations_ID`),UNIQUE INDEX `idtrainStations_UNIQUE` (`trainstations_ID` ASC))ENGINE = InnoDB;
DROP TABLE IF EXISTS `openDataProject`.`departures` ;
CREATE TABLE IF NOT EXISTS `openDataProject`.`departures` (`departures_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,`departure` INT NOT NULL,`trainstation` INT NOT NULL,PRIMARY KEY (`departures_ID`), UNIQUE INDEX `iddepartures_UNIQUE` (`departures_ID` ASC),  INDEX `fk_departures_trainStations_idx` (`trainstation` ASC),  CONSTRAINT `fk_departures_trainStations` FOREIGN KEY (`trainstation`) REFERENCES `openDataProject`.`trainstations` (`trainstations_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;